### ISSUE TITLE
cloud compare error Unable to allocate 1.33 GiB for an array with shape 

### ISSUE THREAD

**Issue by Camiladom1234** [3DFin/3DFin#67] opened 2024-05-24 14:14 UTC
Hi!
 3DFin failed with this error: 
Traceback (most recent call last):
  File "C:\Program Files\CloudCompare\plugins\Python\Lib\site-packages\three_d_fin\gui\application.py", line 70, in run
    self.processing_object.process()
  File "C:\Program Files\CloudCompare\plugins\Python\Lib\site-packages\three_d_fin\processing\abstract_processing.py", line 425, in process
    _, _, voxelated_ground = dm.voxelate(
  File "C:\Program Files\CloudCompare\plugins\Python\Lib\site-packages\dendromatics\voxel\voxel.py", line 126, in voxelate
    unique_code, vox_first_point_id, inverse_id, vox_points = np.unique(
  File "C:\Program Files\CloudCompare\plugins\Python\Lib\site-packages\numpy\lib\arraysetops.py", line 274, in unique
    ret = _unique1d(ar, return_index, return_inverse, return_counts,
  File "C:\Program Files\CloudCompare\plugins\Python\Lib\site-packages\numpy\lib\arraysetops.py", line 334, in _unique1d
    aux = ar[perm]
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 1.33 GiB for an array with shape (179093523,) and data type float64

**Comment by rjanvier** [comment] 2024-05-27 14:07
hi, thank you for the report, this is a duplicate of #65, please try to free memory before running 3Dfin. I will try to introduce a more meaningfull error message in the next release.

**Closed by rjanvier** 2024-05-27 14:07 UTC
Labels: duplicate
